services:
  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - '8090:8090'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/auth/health']
    environment:
      - SERVER_PORT=8090
      - SPRING_PROFILES_ACTIVE=dev
      - DELIUS_ENABLED=true
      - DELIUS_ENDPOINT_URL=http://wiremock:8080/delius
      - DELIUS_ENDPOINT_TIMEOUT=1s
      - DELIUS_CLIENT_CLIENT-ID=delius-auth-api-client
      - DELIUS_CLIENT_CLIENT-SECRET=delius-auth-api-client

  postgresql:
    image: postgres:18
    container_name: postgresql
    networks:
      - hmpps
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '--username=admin', '--dbname=postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_password

  wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps
    restart: always
    ports:
      - '9095:8080'
    volumes:
      - ./wiremock_mappings:/home/wiremock/mappings
    command: '--verbose'

  localstack:
    image: localstack/localstack:4
    networks:
      - hmpps
    container_name: hmpps-mandd-localstack
    ports:
      - '4566:4566'
      - '8999:8080'
    environment:
      - SERVICES=sns,sqs
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - '${TMPDIR:-/tmp/localstack}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

networks:
  hmpps:
